name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: setup
      run: |
        sudo apt-get install libpthread-stubs0-dev
        sudo apt-get install curl
        sudo apt-get install zlib1g-dev

    - name: build
      run: |
        cd MTH_and_HIC
        g++ -O --std=c++0x -o createNormVectorIntra.exe createNormVectorIntra.cpp bestHicScale.c ppNormVector.c straw.cpp thMul.c getHiCInfo.cpp -I. -lz -lcurl -lpthread
