name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: setup
      run: |
        sudo apt-get install libpthread-stubs0-dev
        sudo apt-get install curl
        sudo apt-get install zlib1g-dev
        sudo apt-get install libcurl4-openssl-dev
        sudo apt-get update

    - name: build thScale.exe
      run: |
        cd MTH_and_HIC
        g++ -O --std=c99 -o thScale.exe thMain.c bestHicScale.c thMul.c -lpthread

    - name: build createNormVector.exe
      run: |
        cd MTH_and_HIC
        git clone https://github.com/aidenlab/straw/
        mv straw/C++/* .
        g++ -O --std=c++0x -o createNormVector.exe createNormVector.cpp getMatrix.cpp straw.cpp bestHicScale.c ppNormVector.c thMul.c -I. -lz -lcurl -lpthread
        
