name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        g++ -O3 --std=c99 -shared -c -lm -fPIC -I. -o simpleZero.so simpleZero.c simpleMul.c
        g++ -O3 --std=c99 -o simple.exe simpleMain.c simpleZero.so
